# Import Libraries

In [57]:
import pandas as pd
import numpy as np
import requests
import geopandas as gpd

### Chicago crews able to fill more potholes due to warmer weather

1. Go to the Chicago Data Portal: https://data.cityofchicago.org/
2. Find each dataset. pothole requests and potholes patched.
3. Add a data notes section to your github readme. This should include information about the source of your data, where it came from, how often it is updated, and the period of data it contains (e.g. 2010-present or 2012 to 2019)
4. Lastly, test that this import works. This may take a while as the dataset is large.

My own work for the project -
Work day 4/15

In [58]:
pothole = pd.read_csv("https://data.cityofchicago.org/resource/7as2-ds3y.csv?$limit=1000000")

In [59]:
patched = pd.read_csv("https://data.cityofchicago.org/resource/wqdh-9gek.csv?$limit=1000000")

In [60]:
pothole.head(20)

,creation_date,status,completion_date,service_request_number,type_of_service_request,current_activity,most_recent_action,number_of_potholes_filled_on_block,street_address,zip,x_coordinate,y_coordinate,ward,police_district,community_area,ssa,latitude,longitude,location
0,2018-12-18T00:00:00.000,Open,NaN,18-03387505,Pothole in Street,NaN,NaN,NaN,1145 S FAIRFIELD AVE,60612.0,1.158186e+06,1.894949e+06,28.0,11.0,29.0,NaN,41.866992,-87.694609,"(41.866991991336, -87.694608638672)"
1,2018-12-18T00:00:00.000,Open,NaN,18-03387458,Pothole in Street,NaN,NaN,NaN,908 S CAMPBELL AVE,60612.0,1.159861e+06,1.895934e+06,28.0,11.0,28.0,NaN,41.869927,-87.688710,"(41.869927464401, -87.688710188657)"
2,2018-12-18T00:00:00.000,Open,NaN,18-03387502,Pothole in Street,NaN,NaN,NaN,2421 W 21ST PL,60608.0,1.160590e+06,1.889668e+06,28.0,10.0,31.0,NaN,41.852826,-87.686536,"(41.852826019085, -87.686535678313)"
3,2018-12-18T00:00:00.000,Open - Dup,NaN,18-03388379,Pothole in Street,NaN,NaN,NaN,1959 S TROY ST,60623.0,1.155670e+06,1.890142e+06,24.0,10.0,29.0,NaN,41.853704,-87.703946,"(41.853703821634, -87.703946492923)"
4,2018-12-18T00:00:00.000,Open,NaN,18-03388180,Pothole in Street,NaN,NaN,NaN,4100 S WESTERN BLVD,60609.0,1.161202e+06,1.877426e+06,12.0,9.0,58.0,NaN,41.819247,-87.684305,"(41.819246696086, -87.68430532228)"
5,2018-12-18T00:00:00.000,Open,NaN,18-03388384,Pothole in Street,NaN,NaN,NaN,1959 S TROY ST,60623.0,1.155670e+06,1.890142e+06,24.0,10.0,29.0,NaN,41.853704,-87.703946,"(41.853703821634, -87.703946492923)"
6,2018-12-18T00:00:00.000,Open,NaN,18-03387506,Pothole in Street,NaN,NaN,NaN,1145 S WASHTENAW AVE,60612.0,1.158537e+06,1.894957e+06,28.0,11.0,29.0,NaN,41.867010,-87.693298,"(41.867010107834, -87.693298374569)"
7,2018-12-18T00:00:00.000,Open,NaN,18-03389578,Pothole in Street,NaN,NaN,NaN,2640 N SHEFFIELD AVE,60614.0,1.169170e+06,1.917721e+06,43.0,19.0,7.0,35.0,41.930110,-87.653920,"(41.930110443917, -87.653919807549)"
8,2018-12-18T00:00:00.000,Open,NaN,18-03388378,Pothole in Street,NaN,NaN,NaN,1358 S KEDZIE AVE,60623.0,1.155250e+06,1.893264e+06,24.0,10.0,29.0,NaN,41.862529,-87.705705,"(41.862529376566, -87.705704542865)"
9,2018-12-18T00:00:00.000,Open,NaN,18-03387600,Pothole in Street,NaN,NaN,NaN,2747 N LARAMIE AVE,60639.0,1.141240e+06,1.917871e+06,31.0,25.0,19.0,NaN,41.931008,-87.756259,"(41.931007892382, -87.756258845929)"
10,2018-12-18T00:00:00.000,Open,NaN,18-03388109,Pothole in Street,NaN,NaN,NaN,6300 S NARRAGANSETT AVE,60638.0,1.134831e+06,1.862059e+06,23.0,8.0,64.0,NaN,41.777628,-87.781411,"(41.777628164752, -87.781410620358)"
11,2018-12-18T00:00:00.000,Open - Dup,NaN,18-03387472,Pothole in Street,NaN,NaN,NaN,600 S CENTRAL AVE,60644.0,1.139150e+06,1.896761e+06,29.0,15.0,25.0,NaN,41.872772,-87.764732,"(41.872772222189, -87.764731850479)"
12,2018-12-18T00:00:00.000,Open,NaN,18-03386479,Pothole in Street,NaN,NaN,NaN,1819 W HOWARD ST,60626.0,1.162684e+06,1.950347e+06,49.0,24.0,1.0,19.0,42.019297,-87.676428,"(42.019296595028, -87.676427862387)"
13,2018-12-18T00:00:00.000,Open,NaN,18-03388778,Pothole in Street,NaN,NaN,NaN,8247 S GREEN ST,60620.0,1.172072e+06,1.850163e+06,21.0,6.0,71.0,NaN,41.743768,-87.644910,"(41.743767878412, -87.644910444374)"
14,2018-12-18T00:00:00.000,Open,NaN,18-03387491,Pothole in Street,NaN,NaN,NaN,3530 W GOVERNORS PKWY,60624.0,1.152677e+06,1.902497e+06,27.0,11.0,23.0,NaN,41.888417,-87.714821,"(41.888416873238, -87.714821140269)"
15,2018-12-18T00:00:00.000,Open,NaN,18-03388112,Pothole in Street,NaN,NaN,NaN,5400 N WESTERN AVE,60625.0,1.159364e+06,1.935787e+06,40.0,20.0,4.0,NaN,41.979614,-87.689446,"(41.979613525431, -87.689445831646)"
16,2018-12-18T00:00:00.000,Open,NaN,18-03389580,Pothole in Street,NaN,NaN,NaN,1127 W SCHUBERT AVE,60614.0,1.168322e+06,1.918084e+06,43.0,19.0,7.0,35.0,41.930647,-87.657306,"(41.930647446899, -87.657305830995)"
17,2018-12-18T00:00:00.000,Open,NaN,18-03388657,Pothole in Street,NaN,NaN,NaN,1899 S KOMENSKY AVE,60623.0,1.149689e+06,1.890340e+06,24.0,10.0,29.0,NaN,41.855112,-87.725918,"(41.855111502863, -87.725917692011)"
18,2018-12-18T00:00:00.000,Open,NaN,18-03388493,Pothole in Street,NaN,NaN,NaN,5230 S NEW ENGLAND AVE,60638.0,1.131271e+06,1.869126e+06,23.0,8.0,56.0,NaN,41.796745,-87.794289,"(41.796744707209, -87.79428866381)"
19,2018-12-18T00:00:00.000,Open,NaN,18-03389579,Pothole in Street,NaN,NaN,NaN,2600 N LAKEWOOD AVE,60614.0,1.167191e+06,1.917393e+06,32.0,19.0,7.0,NaN,41.928975,-87.661191,"(41.928975036558, -87.661191076016)"

In [61]:
pothole.tail()

,creation_date,status,completion_date,service_request_number,type_of_service_request,current_activity,most_recent_action,number_of_potholes_filled_on_block,street_address,zip,x_coordinate,y_coordinate,ward,police_district,community_area,ssa,latitude,longitude,location
560473,2010-03-11T00:00:00.000,Completed,2011-03-28T00:00:00.000,10-00317212,Pot Hole in Street,Dispatch Crew,Pothole Patched,5.0,7201 W BELMONT AVE,60634.0,NaN,NaN,36.0,25.0,17.0,NaN,41.937886,-87.806806,"(41.937885966284, -87.8068055064)"
560474,2010-02-26T00:00:00.000,Completed,2011-10-04T00:00:00.000,10-00254019,Pot Hole in Street,NaN,NaN,NaN,1440 S ROCKWELL ST,60608.0,1.159269e+06,1.892879e+06,28.0,10.0,29.0,NaN,41.861757,-87.690973,"(41.861756644625, -87.690972506101)"
560475,2009-08-27T00:00:00.000,Completed,2011-01-25T00:00:00.000,09-01501980,Pot Hole in Street,Site Survey,No Problem Found,80.0,5518 N WAYNE AVE,60640.0,NaN,NaN,48.0,20.0,77.0,NaN,41.982340,-87.663869,"(41.98234020574, -87.663868977471)"
560476,2009-06-17T00:00:00.000,Completed,2011-06-07T00:00:00.000,09-01026546,Pot Hole in Street,Dispatch Crew,Pothole Patched,NaN,3845 W ADDISON ST,60618.0,1.150061e+06,1.923655e+06,30.0,17.0,21.0,NaN,41.946303,-87.724348,"(41.946303283819, -87.724347984027)"
560477,2009-01-12T00:00:00.000,Completed,2011-10-06T00:00:00.000,09-00061329,Pot Hole in Street,Dispatch Crew,Pothole Patched,33.0,2519 S HALSTED ST,60608.0,1.171397e+06,1.887376e+06,11.0,9.0,60.0,NaN,41.846460,-87.646321,"(41.846459969324, -87.646320667697)"

In [62]:
pothole.columns

Index(['creation_date', 'status', 'completion_date', 'service_request_number',
       'type_of_service_request', 'current_activity', 'most_recent_action',
       'number_of_potholes_filled_on_block', 'street_address', 'zip',
       'x_coordinate', 'y_coordinate', 'ward', 'police_district',
       'community_area', 'ssa', 'latitude', 'longitude', 'location'],
      dtype='object')

In [63]:
pothole.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560478 entries, 0 to 560477
Data columns (total 19 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   creation_date                       560478 non-null  object
 1   status                              560478 non-null  object
 2   completion_date                     553130 non-null  object
 3   service_request_number              560478 non-null  object
 4   type_of_service_request             560478 non-null  object
 5   current_activity                    393609 non-null  object
 6   most_recent_action                  391992 non-null  object
 7   number_of_potholes_filled_on_block  399143 non-null  float64
 8   street_address                      560476 non-null  object
 9   zip                                 558160 non-null  float64
 10  x_coordinate                        560004 non-null  float64
 11  y_coordinate                        560004 non-null  float64
 12  ward                                560145 non-null  float64
 13  police_district                     560144 non-null  float64
 14  community_area                      560145 non-null  float64
 15  ssa                                 87611 non-null   float64
 16  latitude                            559602 non-null  float64
 17  longitude                           559602 non-null  float64
 18  location                            559602 non-null  object
dtypes: float64(10), object(9)
memory usage: 81.2+ MB

In [64]:
pothole.shape

(560478, 19)

In [65]:
print(pothole)

                  creation_date      status          completion_date  \
0       2018-12-18T00:00:00.000        Open                      NaN
1       2018-12-18T00:00:00.000        Open                      NaN
2       2018-12-18T00:00:00.000        Open                      NaN
3       2018-12-18T00:00:00.000  Open - Dup                      NaN
4       2018-12-18T00:00:00.000        Open                      NaN
...                         ...         ...                      ...
560473  2010-03-11T00:00:00.000   Completed  2011-03-28T00:00:00.000
560474  2010-02-26T00:00:00.000   Completed  2011-10-04T00:00:00.000
560475  2009-08-27T00:00:00.000   Completed  2011-01-25T00:00:00.000
560476  2009-06-17T00:00:00.000   Completed  2011-06-07T00:00:00.000
560477  2009-01-12T00:00:00.000   Completed  2011-10-06T00:00:00.000

       service_request_number type_of_service_request current_activity  \
0                 18-03387505       Pothole in Street              NaN
1                 18-03387458       Pothole in Street              NaN
2                 18-03387502       Pothole in Street              NaN
3                 18-03388379       Pothole in Street              NaN
4                 18-03388180       Pothole in Street              NaN
...                       ...                     ...              ...
560473            10-00317212      Pot Hole in Street    Dispatch Crew
560474            10-00254019      Pot Hole in Street              NaN
560475            09-01501980      Pot Hole in Street      Site Survey
560476            09-01026546      Pot Hole in Street    Dispatch Crew
560477            09-00061329      Pot Hole in Street    Dispatch Crew

       most_recent_action  number_of_potholes_filled_on_block  \
0                     NaN                                 NaN
1                     NaN                                 NaN
2                     NaN                                 NaN
3                     NaN                                 NaN
4                     NaN                                 NaN
...                   ...                                 ...
560473    Pothole Patched                                 5.0
560474                NaN                                 NaN
560475   No Problem Found                                80.0
560476    Pothole Patched                                 NaN
560477    Pothole Patched                                33.0

              street_address      zip  x_coordinate  y_coordinate  ward  \
0       1145 S FAIRFIELD AVE  60612.0  1.158186e+06  1.894949e+06  28.0
1         908 S CAMPBELL AVE  60612.0  1.159861e+06  1.895934e+06  28.0
2             2421 W 21ST PL  60608.0  1.160590e+06  1.889668e+06  28.0
3             1959 S TROY ST  60623.0  1.155670e+06  1.890142e+06  24.0
4        4100 S WESTERN BLVD  60609.0  1.161202e+06  1.877426e+06  12.0
...                      ...      ...           ...           ...   ...
560473    7201 W BELMONT AVE  60634.0           NaN           NaN  36.0
560474    1440 S ROCKWELL ST  60608.0  1.159269e+06  1.892879e+06  28.0
560475      5518 N WAYNE AVE  60640.0           NaN           NaN  48.0
560476     3845 W ADDISON ST  60618.0  1.150061e+06  1.923655e+06  30.0
560477     2519 S HALSTED ST  60608.0  1.171397e+06  1.887376e+06  11.0

        police_district  community_area  ssa   latitude  longitude  \
0                  11.0            29.0  NaN  41.866992 -87.694609
1                  11.0            28.0  NaN  41.869927 -87.688710
2                  10.0            31.0  NaN  41.852826 -87.686536
3                  10.0            29.0  NaN  41.853704 -87.703946
4                   9.0            58.0  NaN  41.819247 -87.684305
...                 ...             ...  ...        ...        ...
560473             25.0            17.0  NaN  41.937886 -87.806806
560474             10.0            29.0  NaN  41.861757 -87.690973
560475             20.0            77.0  NaN  41.982340 -87.663869
560476             17.0            21.0  NaN  41.946303 -87.724348
560477              9.0            60.0  NaN  41.846460 -87.646321

                                   location
0       (41.866991991336, -87.694608638672)
1       (41.869927464401, -87.688710188657)
2       (41.852826019085, -87.686535678313)
3       (41.853703821634, -87.703946492923)
4        (41.819246696086, -87.68430532228)
...                                     ...
560473    (41.937885966284, -87.8068055064)
560474  (41.861756644625, -87.690972506101)
560475   (41.98234020574, -87.663868977471)
560476  (41.946303283819, -87.724347984027)
560477  (41.846459969324, -87.646320667697)

[560478 rows x 19 columns]

In [66]:
patched.head()

,address,request_date,completion_date,number_of_potholes_filled_on_block,latitude,longitude,location
0,4809 N ROCKWELL ST,2024-04-16T10:07:46.000,2024-04-16T15:19:59.000,8,41.968881,-87.693633,POINT (-87.693633000002 41.968881000941)
1,1158 W WRIGHTWOOD AVE,2024-04-16T15:16:13.000,2024-04-16T15:18:40.000,68,41.929110,-87.658429,POINT (-87.658429500002 41.929110000941)
2,5822 N TALMAN AVE,2024-04-15T14:09:05.000,2024-04-16T15:10:56.000,6,41.987484,-87.695915,POINT (-87.695914500002 41.987484000941)
3,5905 N TALMAN AVE,2024-04-15T14:07:36.000,2024-04-16T15:10:08.000,9,41.988834,-87.695442,POINT (-87.695442000002 41.988834000941)
4,5734 N FAIRFIELD AVE,2024-04-15T14:00:20.000,2024-04-16T15:09:03.000,14,41.985981,-87.698322,POINT (-87.698322000002 41.985981000941)

In [67]:
patched.tail()

,address,request_date,completion_date,number_of_potholes_filled_on_block,latitude,longitude,location
179953,3911 W 61ST ST,2019-02-13T09:14:18.000,2019-02-28T07:14:27.000,4,41.782065,-87.720834,POINT (-87.720834 41.782065)
179954,3908 W 61ST ST,2019-02-13T09:11:06.000,2019-02-28T07:13:30.000,3,41.782588,-87.720808,POINT (-87.720808 41.782588)
179955,3900 W 62ND PL,2019-02-13T09:19:31.000,2019-02-28T07:12:22.000,10,41.779863,-87.720513,POINT (-87.720513 41.779863)
179956,3847 W 61ST PL,2019-02-13T18:50:19.000,2019-02-28T07:11:16.000,15,41.781169,-87.719803,POINT (-87.719803 41.781169)
179957,6400 S MAJOR Avenue,2018-08-01T15:13:33.000,2019-01-09T11:36:02.000,16,41.776112,-87.764137,POINT (-87.764136509305 41.776112376302)

In [68]:
patched.columns

Index(['address', 'request_date', 'completion_date',
       'number_of_potholes_filled_on_block', 'latitude', 'longitude',
       'location'],
      dtype='object')

In [69]:
patched.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179958 entries, 0 to 179957
Data columns (total 7 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   address                             179958 non-null  object
 1   request_date                        179958 non-null  object
 2   completion_date                     179958 non-null  object
 3   number_of_potholes_filled_on_block  179958 non-null  int64
 4   latitude                            179489 non-null  float64
 5   longitude                           179489 non-null  float64
 6   location                            179489 non-null  object
dtypes: float64(2), int64(1), object(4)
memory usage: 9.6+ MB

In [70]:
patched.shape

(179958, 7)

In [71]:
print(patched)

                      address             request_date  \
0          4809 N ROCKWELL ST  2024-04-16T10:07:46.000
1       1158 W WRIGHTWOOD AVE  2024-04-16T15:16:13.000
2           5822 N TALMAN AVE  2024-04-15T14:09:05.000
3           5905 N TALMAN AVE  2024-04-15T14:07:36.000
4        5734 N FAIRFIELD AVE  2024-04-15T14:00:20.000
...                       ...                      ...
179953         3911 W 61ST ST  2019-02-13T09:14:18.000
179954         3908 W 61ST ST  2019-02-13T09:11:06.000
179955         3900 W 62ND PL  2019-02-13T09:19:31.000
179956         3847 W 61ST PL  2019-02-13T18:50:19.000
179957    6400 S MAJOR Avenue  2018-08-01T15:13:33.000

                completion_date  number_of_potholes_filled_on_block  \
0       2024-04-16T15:19:59.000                                   8
1       2024-04-16T15:18:40.000                                  68
2       2024-04-16T15:10:56.000                                   6
3       2024-04-16T15:10:08.000                                   9
4       2024-04-16T15:09:03.000                                  14
...                         ...                                 ...
179953  2019-02-28T07:14:27.000                                   4
179954  2019-02-28T07:13:30.000                                   3
179955  2019-02-28T07:12:22.000                                  10
179956  2019-02-28T07:11:16.000                                  15
179957  2019-01-09T11:36:02.000                                  16

         latitude  longitude                                  location
0       41.968881 -87.693633  POINT (-87.693633000002 41.968881000941)
1       41.929110 -87.658429  POINT (-87.658429500002 41.929110000941)
2       41.987484 -87.695915  POINT (-87.695914500002 41.987484000941)
3       41.988834 -87.695442  POINT (-87.695442000002 41.988834000941)
4       41.985981 -87.698322  POINT (-87.698322000002 41.985981000941)
...           ...        ...                                       ...
179953  41.782065 -87.720834              POINT (-87.720834 41.782065)
179954  41.782588 -87.720808              POINT (-87.720808 41.782588)
179955  41.779863 -87.720513              POINT (-87.720513 41.779863)
179956  41.781169 -87.719803              POINT (-87.719803 41.781169)
179957  41.776112 -87.764137  POINT (-87.764136509305 41.776112376302)

[179958 rows x 7 columns]

Project work in group - Work Day 4/16

Must convert data types at least once
 pd.to_numeric()
pd.to_datetime()

In [72]:
patched['request_date'] = pd.to_datetime(patched['request_date'])

In [73]:
patched['Year'] = patched['request_date'].dt.year

In [74]:
patched['Month'] = patched['request_date'].dt.year

In [75]:
patched['Weekday'] = patched['request_date'].dt.year

In [76]:
patched['Day'] = patched['request_date'].dt.year

In [77]:
patched['Hour'] = patched['request_date'].dt.year

In [78]:
patched['Minute'] = patched['request_date'].dt.year

In [79]:
patched.columns

Index(['address', 'request_date', 'completion_date',
       'number_of_potholes_filled_on_block', 'latitude', 'longitude',
       'location', 'Year', 'Month', 'Weekday', 'Day', 'Hour', 'Minute'],
      dtype='object')

Work Day 4/17

Must use at least three groupbys()
Use at least two: mean(), median, sum(), min(), max(), count(), size(), first(), last()

In [80]:
patched.groupby('number_of_potholes_filled_on_block').size().sort_values(ascending = False)

number_of_potholes_filled_on_block
1      20562
2      18070
3      14262
5      12535
4      12006
       ...
212        1
214        1
215        1
218        1
467        1
Length: 230, dtype: int64

In [81]:
pothole.groupby('ward')['type_of_service_request'].count().sort_values(ascending = False)

ward
41.0    21637
45.0    16788
19.0    16534
23.0    16398
32.0    16173
13.0    15765
39.0    15699
8.0     15336
42.0    14730
34.0    14528
21.0    14126
2.0     13790
18.0    13761
36.0    13687
27.0    13221
38.0    12878
50.0    12760
14.0    12244
10.0    12146
40.0    11965
29.0    11730
6.0     11460
35.0    10732
28.0    10693
25.0    10621
1.0     10545
5.0     10438
9.0     10380
11.0     9743
12.0     9620
49.0     9551
47.0     9458
31.0     9351
17.0     9055
24.0     9044
37.0     8942
30.0     8436
26.0     8358
43.0     8231
7.0      7997
33.0     7922
16.0     7825
3.0      7611
20.0     7541
15.0     7334
48.0     7076
4.0      7042
22.0     6966
44.0     6373
46.0     4340
0.0      1564
Name: type_of_service_request, dtype: int64

Must use at least one conditional logic
If/else
 np.where()
np.select()

In [82]:
duplicates = pothole.duplicated()

In [83]:
num_duplicates = duplicates.sum()

In [84]:
if num_duplicates > 0:
  print(f'there are {num_duplicates} duplicate rows in the dataset.')
else:
  print('there are no duplicate rows in the dataet.')

there are 2 duplicate rows in the dataset.

In [85]:
#string.split with street name to see which has the most

In [86]:
pothole['street_address'].unique()

array(['1145 S FAIRFIELD AVE', '908 S CAMPBELL AVE', '2421 W 21ST PL',
       ..., '1599 N ELK GROVE AVE', '801 W 111TH ST',
       '1440 S ROCKWELL ST'], dtype=object)

In [100]:
pothole['street_address'].str.split()

0         [1145, S, FAIRFIELD, AVE]
1           [908, S, CAMPBELL, AVE]
2               [2421, W, 21ST, PL]
3               [1959, S, TROY, ST]
4          [4100, S, WESTERN, BLVD]
                    ...
560473      [7201, W, BELMONT, AVE]
560474      [1440, S, ROCKWELL, ST]
560475        [5518, N, WAYNE, AVE]
560476       [3845, W, ADDISON, ST]
560477       [2519, S, HALSTED, ST]
Name: street_address, Length: 560478, dtype: object

In [87]:
pothole['street_address'].value_counts().reset_index()

                 street_address  count
0             55 W JACKSON BLVD    386
1            1800 S WESTERN AVE    316
2          8300 S VINCENNES AVE    313
3       7500 S STONY ISLAND AVE    274
4       9500 S STONY ISLAND AVE    268
...                         ...    ...
250602         3420 W NORTH AVE      1
250603      2754 W ROOSEVELT RD      1
250604      3932 W LAWRENCE AVE      1
250605           138 E 123RD ST      1
250606       1440 S ROCKWELL ST      1

[250607 rows x 2 columns]

In [88]:
duplicates_mask = pothole.duplicated(subset = 'service_request_number', keep=False)

In [89]:
pothole['is_duplicated'] = duplicates_mask

In [90]:
pothole.head()

,creation_date,status,completion_date,service_request_number,type_of_service_request,current_activity,most_recent_action,number_of_potholes_filled_on_block,street_address,zip,x_coordinate,y_coordinate,ward,police_district,community_area,ssa,latitude,longitude,location,is_duplicated
0,2018-12-18T00:00:00.000,Open,NaN,18-03387505,Pothole in Street,NaN,NaN,NaN,1145 S FAIRFIELD AVE,60612.0,1.158186e+06,1.894949e+06,28.0,11.0,29.0,NaN,41.866992,-87.694609,"(41.866991991336, -87.694608638672)",False
1,2018-12-18T00:00:00.000,Open,NaN,18-03387458,Pothole in Street,NaN,NaN,NaN,908 S CAMPBELL AVE,60612.0,1.159861e+06,1.895934e+06,28.0,11.0,28.0,NaN,41.869927,-87.688710,"(41.869927464401, -87.688710188657)",False
2,2018-12-18T00:00:00.000,Open,NaN,18-03387502,Pothole in Street,NaN,NaN,NaN,2421 W 21ST PL,60608.0,1.160590e+06,1.889668e+06,28.0,10.0,31.0,NaN,41.852826,-87.686536,"(41.852826019085, -87.686535678313)",False
3,2018-12-18T00:00:00.000,Open - Dup,NaN,18-03388379,Pothole in Street,NaN,NaN,NaN,1959 S TROY ST,60623.0,1.155670e+06,1.890142e+06,24.0,10.0,29.0,NaN,41.853704,-87.703946,"(41.853703821634, -87.703946492923)",False
4,2018-12-18T00:00:00.000,Open,NaN,18-03388180,Pothole in Street,NaN,NaN,NaN,4100 S WESTERN BLVD,60609.0,1.161202e+06,1.877426e+06,12.0,9.0,58.0,NaN,41.819247,-87.684305,"(41.819246696086, -87.68430532228)",False

Did this even drop or point out the duplicated rows?

In [92]:
status_dup = pothole['status'].duplicated()

In [93]:
duplicate_rows = pothole[status_dup]

In [94]:
print(duplicate_rows)

                  creation_date     status          completion_date  \
1       2018-12-18T00:00:00.000       Open                      NaN
2       2018-12-18T00:00:00.000       Open                      NaN
4       2018-12-18T00:00:00.000       Open                      NaN
5       2018-12-18T00:00:00.000       Open                      NaN
6       2018-12-18T00:00:00.000       Open                      NaN
...                         ...        ...                      ...
560473  2010-03-11T00:00:00.000  Completed  2011-03-28T00:00:00.000
560474  2010-02-26T00:00:00.000  Completed  2011-10-04T00:00:00.000
560475  2009-08-27T00:00:00.000  Completed  2011-01-25T00:00:00.000
560476  2009-06-17T00:00:00.000  Completed  2011-06-07T00:00:00.000
560477  2009-01-12T00:00:00.000  Completed  2011-10-06T00:00:00.000

       service_request_number type_of_service_request current_activity  \
1                 18-03387458       Pothole in Street              NaN
2                 18-03387502       Pothole in Street              NaN
4                 18-03388180       Pothole in Street              NaN
5                 18-03388384       Pothole in Street              NaN
6                 18-03387506       Pothole in Street              NaN
...                       ...                     ...              ...
560473            10-00317212      Pot Hole in Street    Dispatch Crew
560474            10-00254019      Pot Hole in Street              NaN
560475            09-01501980      Pot Hole in Street      Site Survey
560476            09-01026546      Pot Hole in Street    Dispatch Crew
560477            09-00061329      Pot Hole in Street    Dispatch Crew

       most_recent_action  number_of_potholes_filled_on_block  \
1                     NaN                                 NaN
2                     NaN                                 NaN
4                     NaN                                 NaN
5                     NaN                                 NaN
6                     NaN                                 NaN
...                   ...                                 ...
560473    Pothole Patched                                 5.0
560474                NaN                                 NaN
560475   No Problem Found                                80.0
560476    Pothole Patched                                 NaN
560477    Pothole Patched                                33.0

              street_address      zip  x_coordinate  y_coordinate  ward  \
1         908 S CAMPBELL AVE  60612.0  1.159861e+06  1.895934e+06  28.0
2             2421 W 21ST PL  60608.0  1.160590e+06  1.889668e+06  28.0
4        4100 S WESTERN BLVD  60609.0  1.161202e+06  1.877426e+06  12.0
5             1959 S TROY ST  60623.0  1.155670e+06  1.890142e+06  24.0
6       1145 S WASHTENAW AVE  60612.0  1.158537e+06  1.894957e+06  28.0
...                      ...      ...           ...           ...   ...
560473    7201 W BELMONT AVE  60634.0           NaN           NaN  36.0
560474    1440 S ROCKWELL ST  60608.0  1.159269e+06  1.892879e+06  28.0
560475      5518 N WAYNE AVE  60640.0           NaN           NaN  48.0
560476     3845 W ADDISON ST  60618.0  1.150061e+06  1.923655e+06  30.0
560477     2519 S HALSTED ST  60608.0  1.171397e+06  1.887376e+06  11.0

        police_district  community_area  ssa   latitude  longitude  \
1                  11.0            28.0  NaN  41.869927 -87.688710
2                  10.0            31.0  NaN  41.852826 -87.686536
4                   9.0            58.0  NaN  41.819247 -87.684305
5                  10.0            29.0  NaN  41.853704 -87.703946
6                  11.0            29.0  NaN  41.867010 -87.693298
...                 ...             ...  ...        ...        ...
560473             25.0            17.0  NaN  41.937886 -87.806806
560474             10.0            29.0  NaN  41.861757 -87.690973
560475             20.0            77.0  NaN  41.982340 -87.663869
560476             17.0            21.0  NaN  41.946303 -87.724348
560477              9.0            60.0  NaN  41.846460 -87.646321

                                   location  is_duplicated
1       (41.869927464401, -87.688710188657)          False
2       (41.852826019085, -87.686535678313)          False
4        (41.819246696086, -87.68430532228)          False
5       (41.853703821634, -87.703946492923)          False
6       (41.867010107834, -87.693298374569)          False
...                                     ...            ...
560473    (41.937885966284, -87.8068055064)          False
560474  (41.861756644625, -87.690972506101)          False
560475   (41.98234020574, -87.663868977471)          False
560476  (41.946303283819, -87.724347984027)          False
560477  (41.846459969324, -87.646320667697)          False

[560474 rows x 20 columns]

In [96]:
pothole_no_status_dup = pothole.drop_duplicates()

In [97]:
pothole_no_status_dup.reset_index()

,index,creation_date,status,completion_date,service_request_number,type_of_service_request,current_activity,most_recent_action,number_of_potholes_filled_on_block,street_address,...,x_coordinate,y_coordinate,ward,police_district,community_area,ssa,latitude,longitude,location,is_duplicated
0,0,2018-12-18T00:00:00.000,Open,NaN,18-03387505,Pothole in Street,NaN,NaN,NaN,1145 S FAIRFIELD AVE,...,1.158186e+06,1.894949e+06,28.0,11.0,29.0,NaN,41.866992,-87.694609,"(41.866991991336, -87.694608638672)",False
1,1,2018-12-18T00:00:00.000,Open,NaN,18-03387458,Pothole in Street,NaN,NaN,NaN,908 S CAMPBELL AVE,...,1.159861e+06,1.895934e+06,28.0,11.0,28.0,NaN,41.869927,-87.688710,"(41.869927464401, -87.688710188657)",False
2,2,2018-12-18T00:00:00.000,Open,NaN,18-03387502,Pothole in Street,NaN,NaN,NaN,2421 W 21ST PL,...,1.160590e+06,1.889668e+06,28.0,10.0,31.0,NaN,41.852826,-87.686536,"(41.852826019085, -87.686535678313)",False
3,3,2018-12-18T00:00:00.000,Open - Dup,NaN,18-03388379,Pothole in Street,NaN,NaN,NaN,1959 S TROY ST,...,1.155670e+06,1.890142e+06,24.0,10.0,29.0,NaN,41.853704,-87.703946,"(41.853703821634, -87.703946492923)",False
4,4,2018-12-18T00:00:00.000,Open,NaN,18-03388180,Pothole in Street,NaN,NaN,NaN,4100 S WESTERN BLVD,...,1.161202e+06,1.877426e+06,12.0,9.0,58.0,NaN,41.819247,-87.684305,"(41.819246696086, -87.68430532228)",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
560471,560473,2010-03-11T00:00:00.000,Completed,2011-03-28T00:00:00.000,10-00317212,Pot Hole in Street,Dispatch Crew,Pothole Patched,5.0,7201 W BELMONT AVE,...,NaN,NaN,36.0,25.0,17.0,NaN,41.937886,-87.806806,"(41.937885966284, -87.8068055064)",False
560472,560474,2010-02-26T00:00:00.000,Completed,2011-10-04T00:00:00.000,10-00254019,Pot Hole in Street,NaN,NaN,NaN,1440 S ROCKWELL ST,...,1.159269e+06,1.892879e+06,28.0,10.0,29.0,NaN,41.861757,-87.690973,"(41.861756644625, -87.690972506101)",False
560473,560475,2009-08-27T00:00:00.000,Completed,2011-01-25T00:00:00.000,09-01501980,Pot Hole in Street,Site Survey,No Problem Found,80.0,5518 N WAYNE AVE,...,NaN,NaN,48.0,20.0,77.0,NaN,41.982340,-87.663869,"(41.98234020574, -87.663868977471)",False
560474,560476,2009-06-17T00:00:00.000,Completed,2011-06-07T00:00:00.000,09-01026546,Pot Hole in Street,Dispatch Crew,Pothole Patched,NaN,3845 W ADDISON ST,...,1.150061e+06,1.923655e+06,30.0,17.0,21.0,NaN,41.946303,-87.724348,"(41.946303283819, -87.724347984027)",False
560475,560477,2009-01-12T00:00:00.000,Completed,2011-10-06T00:00:00.000,09-00061329,Pot Hole in Street,Dispatch Crew,Pothole Patched,33.0,2519 S HALSTED ST,...,1.171397e+06,1.887376e+06,11.0,9.0,60.0,NaN,41.846460,-87.646321,"(41.846459969324, -87.646320667697)",False